// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/report.proto

package report

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Report_ExportExcel_FullMethodName     = "/report.Report/ExportExcel"
	Report_ExportPDF_FullMethodName       = "/report.Report/ExportPDF"
	Report_ExportSinglePDF_FullMethodName = "/report.Report/ExportSinglePDF"
)

// ReportClient is the client API for Report service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 报告生成服务
type ReportClient interface {
	// 导出Excel报告
	ExportExcel(ctx context.Context, in *ExportReq, opts ...grpc.CallOption) (*ExportResp, error)
	// 导出PDF报告
	ExportPDF(ctx context.Context, in *ExportReq, opts ...grpc.CallOption) (*ExportResp, error)
	// 导出单条PDF报告
	ExportSinglePDF(ctx context.Context, in *SingleExportReq, opts ...grpc.CallOption) (*ExportResp, error)
}

type reportClient struct {
	cc grpc.ClientConnInterface
}

func NewReportClient(cc grpc.ClientConnInterface) ReportClient {
	return &reportClient{cc}
}

func (c *reportClient) ExportExcel(ctx context.Context, in *ExportReq, opts ...grpc.CallOption) (*ExportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResp)
	err := c.cc.Invoke(ctx, Report_ExportExcel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportClient) ExportPDF(ctx context.Context, in *ExportReq, opts ...grpc.CallOption) (*ExportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResp)
	err := c.cc.Invoke(ctx, Report_ExportPDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportClient) ExportSinglePDF(ctx context.Context, in *SingleExportReq, opts ...grpc.CallOption) (*ExportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResp)
	err := c.cc.Invoke(ctx, Report_ExportSinglePDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServer is the server API for Report service.
// All implementations must embed UnimplementedReportServer
// for forward compatibility.
//
// 报告生成服务
type ReportServer interface {
	// 导出Excel报告
	ExportExcel(context.Context, *ExportReq) (*ExportResp, error)
	// 导出PDF报告
	ExportPDF(context.Context, *ExportReq) (*ExportResp, error)
	// 导出单条PDF报告
	ExportSinglePDF(context.Context, *SingleExportReq) (*ExportResp, error)
	mustEmbedUnimplementedReportServer()
}

// UnimplementedReportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReportServer struct{}

func (UnimplementedReportServer) ExportExcel(context.Context, *ExportReq) (*ExportResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportExcel not implemented")
}
func (UnimplementedReportServer) ExportPDF(context.Context, *ExportReq) (*ExportResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportPDF not implemented")
}
func (UnimplementedReportServer) ExportSinglePDF(context.Context, *SingleExportReq) (*ExportResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportSinglePDF not implemented")
}
func (UnimplementedReportServer) mustEmbedUnimplementedReportServer() {}
func (UnimplementedReportServer) testEmbeddedByValue()                {}

// UnsafeReportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportServer will
// result in compilation errors.
type UnsafeReportServer interface {
	mustEmbedUnimplementedReportServer()
}

func RegisterReportServer(s grpc.ServiceRegistrar, srv ReportServer) {
	// If the following call panics, it indicates UnimplementedReportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Report_ServiceDesc, srv)
}

func _Report_ExportExcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).ExportExcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Report_ExportExcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).ExportExcel(ctx, req.(*ExportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Report_ExportPDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).ExportPDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Report_ExportPDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).ExportPDF(ctx, req.(*ExportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Report_ExportSinglePDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleExportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).ExportSinglePDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Report_ExportSinglePDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).ExportSinglePDF(ctx, req.(*SingleExportReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Report_ServiceDesc is the grpc.ServiceDesc for Report service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Report_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "report.Report",
	HandlerType: (*ReportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportExcel",
			Handler:    _Report_ExportExcel_Handler,
		},
		{
			MethodName: "ExportPDF",
			Handler:    _Report_ExportPDF_Handler,
		},
		{
			MethodName: "ExportSinglePDF",
			Handler:    _Report_ExportSinglePDF_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/report.proto",
}
