// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/report.proto

package report

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	IsGlandFace   bool                   `protobuf:"varint,4,opt,name=is_gland_face,json=isGlandFace,proto3" json:"is_gland_face,omitempty"`
	HasFilter     bool                   `protobuf:"varint,5,opt,name=has_filter,json=hasFilter,proto3" json:"has_filter,omitempty"`
	Level         string                 `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportReq) Reset() {
	*x = ExportReq{}
	mi := &file_proto_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReq) ProtoMessage() {}

func (x *ExportReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReq.ProtoReflect.Descriptor instead.
func (*ExportReq) Descriptor() ([]byte, []int) {
	return file_proto_report_proto_rawDescGZIP(), []int{0}
}

func (x *ExportReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ExportReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ExportReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ExportReq) GetIsGlandFace() bool {
	if x != nil {
		return x.IsGlandFace
	}
	return false
}

func (x *ExportReq) GetHasFilter() bool {
	if x != nil {
		return x.HasFilter
	}
	return false
}

func (x *ExportReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type SingleExportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultId      int64                  `protobuf:"varint,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleExportReq) Reset() {
	*x = SingleExportReq{}
	mi := &file_proto_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleExportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleExportReq) ProtoMessage() {}

func (x *SingleExportReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleExportReq.ProtoReflect.Descriptor instead.
func (*SingleExportReq) Descriptor() ([]byte, []int) {
	return file_proto_report_proto_rawDescGZIP(), []int{1}
}

func (x *SingleExportReq) GetResultId() int64 {
	if x != nil {
		return x.ResultId
	}
	return 0
}

func (x *SingleExportReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ExportResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	FileData      []byte                 `protobuf:"bytes,3,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResp) Reset() {
	*x = ExportResp{}
	mi := &file_proto_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResp) ProtoMessage() {}

func (x *ExportResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResp.ProtoReflect.Descriptor instead.
func (*ExportResp) Descriptor() ([]byte, []int) {
	return file_proto_report_proto_rawDescGZIP(), []int{2}
}

func (x *ExportResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ExportResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ExportResp) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *ExportResp) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ExportResp) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_proto_report_proto protoreflect.FileDescriptor

const file_proto_report_proto_rawDesc = "" +
	"\n" +
	"\x12proto/report.proto\x12\x06report\"\xb7\x01\n" +
	"\tExportReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12\"\n" +
	"\ris_gland_face\x18\x04 \x01(\bR\visGlandFace\x12\x1d\n" +
	"\n" +
	"has_filter\x18\x05 \x01(\bR\thasFilter\x12\x14\n" +
	"\x05level\x18\x06 \x01(\tR\x05level\"G\n" +
	"\x0fSingleExportReq\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\x03R\bresultId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x8e\x01\n" +
	"\n" +
	"ExportResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1b\n" +
	"\tfile_data\x18\x03 \x01(\fR\bfileData\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType2\xb2\x01\n" +
	"\x06Report\x124\n" +
	"\vExportExcel\x12\x11.report.ExportReq\x1a\x12.report.ExportResp\x122\n" +
	"\tExportPDF\x12\x11.report.ExportReq\x1a\x12.report.ExportResp\x12>\n" +
	"\x0fExportSinglePDF\x12\x17.report.SingleExportReq\x1a\x12.report.ExportRespB\x1fZ\x1dfaceTest/backend/proto/reportb\x06proto3"

var (
	file_proto_report_proto_rawDescOnce sync.Once
	file_proto_report_proto_rawDescData []byte
)

func file_proto_report_proto_rawDescGZIP() []byte {
	file_proto_report_proto_rawDescOnce.Do(func() {
		file_proto_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_report_proto_rawDesc), len(file_proto_report_proto_rawDesc)))
	})
	return file_proto_report_proto_rawDescData
}

var file_proto_report_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_report_proto_goTypes = []any{
	(*ExportReq)(nil),       // 0: report.ExportReq
	(*SingleExportReq)(nil), // 1: report.SingleExportReq
	(*ExportResp)(nil),      // 2: report.ExportResp
}
var file_proto_report_proto_depIdxs = []int32{
	0, // 0: report.Report.ExportExcel:input_type -> report.ExportReq
	0, // 1: report.Report.ExportPDF:input_type -> report.ExportReq
	1, // 2: report.Report.ExportSinglePDF:input_type -> report.SingleExportReq
	2, // 3: report.Report.ExportExcel:output_type -> report.ExportResp
	2, // 4: report.Report.ExportPDF:output_type -> report.ExportResp
	2, // 5: report.Report.ExportSinglePDF:output_type -> report.ExportResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_report_proto_init() }
func file_proto_report_proto_init() {
	if File_proto_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_report_proto_rawDesc), len(file_proto_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_report_proto_goTypes,
		DependencyIndexes: file_proto_report_proto_depIdxs,
		MessageInfos:      file_proto_report_proto_msgTypes,
	}.Build()
	File_proto_report_proto = out.File
	file_proto_report_proto_goTypes = nil
	file_proto_report_proto_depIdxs = nil
}
