// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/diagnosis/diagnosis.proto

package diagnosis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitDiagnosisReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ImagePath     string                 `protobuf:"bytes,2,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDiagnosisReq) Reset() {
	*x = SubmitDiagnosisReq{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDiagnosisReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDiagnosisReq) ProtoMessage() {}

func (x *SubmitDiagnosisReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDiagnosisReq.ProtoReflect.Descriptor instead.
func (*SubmitDiagnosisReq) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitDiagnosisReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitDiagnosisReq) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *SubmitDiagnosisReq) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *SubmitDiagnosisReq) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *SubmitDiagnosisReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

type SubmitDiagnosisResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TaskId        int64                  `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskNo        string                 `protobuf:"bytes,4,opt,name=task_no,json=taskNo,proto3" json:"task_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDiagnosisResp) Reset() {
	*x = SubmitDiagnosisResp{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDiagnosisResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDiagnosisResp) ProtoMessage() {}

func (x *SubmitDiagnosisResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDiagnosisResp.ProtoReflect.Descriptor instead.
func (*SubmitDiagnosisResp) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitDiagnosisResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SubmitDiagnosisResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SubmitDiagnosisResp) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *SubmitDiagnosisResp) GetTaskNo() string {
	if x != nil {
		return x.TaskNo
	}
	return ""
}

type GetResultReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultId      int64                  `protobuf:"varint,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultReq) Reset() {
	*x = GetResultReq{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultReq) ProtoMessage() {}

func (x *GetResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultReq.ProtoReflect.Descriptor instead.
func (*GetResultReq) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{2}
}

func (x *GetResultReq) GetResultId() int64 {
	if x != nil {
		return x.ResultId
	}
	return 0
}

func (x *GetResultReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DiagnosisResultResp struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId                   int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId                   int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ImagePath                string                 `protobuf:"bytes,4,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	ImageUrl                 string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsGlandFace              bool                   `protobuf:"varint,6,opt,name=is_gland_face,json=isGlandFace,proto3" json:"is_gland_face,omitempty"`
	Level                    string                 `protobuf:"bytes,7,opt,name=level,proto3" json:"level,omitempty"`
	VisualizationDescription string                 `protobuf:"bytes,9,opt,name=visualization_description,json=visualizationDescription,proto3" json:"visualization_description,omitempty"`
	ReferenceCases           string                 `protobuf:"bytes,10,opt,name=reference_cases,json=referenceCases,proto3" json:"reference_cases,omitempty"`
	TestTime                 string                 `protobuf:"bytes,11,opt,name=test_time,json=testTime,proto3" json:"test_time,omitempty"`
	SkippedImages            string                 `protobuf:"bytes,12,opt,name=skipped_images,json=skippedImages,proto3" json:"skipped_images,omitempty"` // 多图诊断中被剔除（未检测到人脸）的图片路径 JSON 数组
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DiagnosisResultResp) Reset() {
	*x = DiagnosisResultResp{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosisResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosisResultResp) ProtoMessage() {}

func (x *DiagnosisResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosisResultResp.ProtoReflect.Descriptor instead.
func (*DiagnosisResultResp) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{3}
}

func (x *DiagnosisResultResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DiagnosisResultResp) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *DiagnosisResultResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DiagnosisResultResp) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *DiagnosisResultResp) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *DiagnosisResultResp) GetIsGlandFace() bool {
	if x != nil {
		return x.IsGlandFace
	}
	return false
}

func (x *DiagnosisResultResp) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *DiagnosisResultResp) GetVisualizationDescription() string {
	if x != nil {
		return x.VisualizationDescription
	}
	return ""
}

func (x *DiagnosisResultResp) GetReferenceCases() string {
	if x != nil {
		return x.ReferenceCases
	}
	return ""
}

func (x *DiagnosisResultResp) GetTestTime() string {
	if x != nil {
		return x.TestTime
	}
	return ""
}

func (x *DiagnosisResultResp) GetSkippedImages() string {
	if x != nil {
		return x.SkippedImages
	}
	return ""
}

type GetTaskStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusReq) Reset() {
	*x = GetTaskStatusReq{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusReq) ProtoMessage() {}

func (x *GetTaskStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusReq.ProtoReflect.Descriptor instead.
func (*GetTaskStatusReq) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskStatusReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type GetTaskStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskNo        string                 `protobuf:"bytes,2,opt,name=task_no,json=taskNo,proto3" json:"task_no,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	RetryCount    int32                  `protobuf:"varint,4,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusResp) Reset() {
	*x = GetTaskStatusResp{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusResp) ProtoMessage() {}

func (x *GetTaskStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusResp.ProtoReflect.Descriptor instead.
func (*GetTaskStatusResp) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskStatusResp) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetTaskStatusResp) GetTaskNo() string {
	if x != nil {
		return x.TaskNo
	}
	return ""
}

func (x *GetTaskStatusResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetTaskStatusResp) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *GetTaskStatusResp) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListResultsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	IsGlandFace   bool                   `protobuf:"varint,6,opt,name=is_gland_face,json=isGlandFace,proto3" json:"is_gland_face,omitempty"`
	HasFilter     bool                   `protobuf:"varint,7,opt,name=has_filter,json=hasFilter,proto3" json:"has_filter,omitempty"`
	Level         string                 `protobuf:"bytes,8,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResultsReq) Reset() {
	*x = ListResultsReq{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResultsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResultsReq) ProtoMessage() {}

func (x *ListResultsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResultsReq.ProtoReflect.Descriptor instead.
func (*ListResultsReq) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{6}
}

func (x *ListResultsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListResultsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResultsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListResultsReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ListResultsReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ListResultsReq) GetIsGlandFace() bool {
	if x != nil {
		return x.IsGlandFace
	}
	return false
}

func (x *ListResultsReq) GetHasFilter() bool {
	if x != nil {
		return x.HasFilter
	}
	return false
}

func (x *ListResultsReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type ListResultsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*DiagnosisResultResp `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResultsResp) Reset() {
	*x = ListResultsResp{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResultsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResultsResp) ProtoMessage() {}

func (x *ListResultsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResultsResp.ProtoReflect.Descriptor instead.
func (*ListResultsResp) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{7}
}

func (x *ListResultsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListResultsResp) GetRecords() []*DiagnosisResultResp {
	if x != nil {
		return x.Records
	}
	return nil
}

type DeleteResultReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultId      int64                  `protobuf:"varint,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResultReq) Reset() {
	*x = DeleteResultReq{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResultReq) ProtoMessage() {}

func (x *DeleteResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResultReq.ProtoReflect.Descriptor instead.
func (*DeleteResultReq) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResultReq) GetResultId() int64 {
	if x != nil {
		return x.ResultId
	}
	return 0
}

func (x *DeleteResultReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteResultResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResultResp) Reset() {
	*x = DeleteResultResp{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResultResp) ProtoMessage() {}

func (x *DeleteResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResultResp.ProtoReflect.Descriptor instead.
func (*DeleteResultResp) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResultResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteResultResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BatchDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteReq) Reset() {
	*x = BatchDeleteReq{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteReq) ProtoMessage() {}

func (x *BatchDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteReq.ProtoReflect.Descriptor instead.
func (*BatchDeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{10}
}

func (x *BatchDeleteReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *BatchDeleteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type BatchDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	DeletedCount  int32                  `protobuf:"varint,3,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteResp) Reset() {
	*x = BatchDeleteResp{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteResp) ProtoMessage() {}

func (x *BatchDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteResp.ProtoReflect.Descriptor instead.
func (*BatchDeleteResp) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{11}
}

func (x *BatchDeleteResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BatchDeleteResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BatchDeleteResp) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type UpdateResultReq struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ResultId                 int64                  `protobuf:"varint,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	UserId                   int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Level                    string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	VisualizationDescription string                 `protobuf:"bytes,4,opt,name=visualization_description,json=visualizationDescription,proto3" json:"visualization_description,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UpdateResultReq) Reset() {
	*x = UpdateResultReq{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResultReq) ProtoMessage() {}

func (x *UpdateResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResultReq.ProtoReflect.Descriptor instead.
func (*UpdateResultReq) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateResultReq) GetResultId() int64 {
	if x != nil {
		return x.ResultId
	}
	return 0
}

func (x *UpdateResultReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateResultReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *UpdateResultReq) GetVisualizationDescription() string {
	if x != nil {
		return x.VisualizationDescription
	}
	return ""
}

type UpdateResultResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResultResp) Reset() {
	*x = UpdateResultResp{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResultResp) ProtoMessage() {}

func (x *UpdateResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResultResp.ProtoReflect.Descriptor instead.
func (*UpdateResultResp) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateResultResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateResultResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type StatisticsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsReq) Reset() {
	*x = StatisticsReq{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsReq) ProtoMessage() {}

func (x *StatisticsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsReq.ProtoReflect.Descriptor instead.
func (*StatisticsReq) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{14}
}

func (x *StatisticsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StatisticsReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *StatisticsReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type StatisticsResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalTests        int64                  `protobuf:"varint,1,opt,name=total_tests,json=totalTests,proto3" json:"total_tests,omitempty"`
	GlandFaceCount    int64                  `protobuf:"varint,2,opt,name=gland_face_count,json=glandFaceCount,proto3" json:"gland_face_count,omitempty"`
	NonGlandFaceCount int64                  `protobuf:"varint,3,opt,name=non_gland_face_count,json=nonGlandFaceCount,proto3" json:"non_gland_face_count,omitempty"`
	TrendData         string                 `protobuf:"bytes,5,opt,name=trend_data,json=trendData,proto3" json:"trend_data,omitempty"`
	LevelData         string                 `protobuf:"bytes,6,opt,name=level_data,json=levelData,proto3" json:"level_data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatisticsResp) Reset() {
	*x = StatisticsResp{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsResp) ProtoMessage() {}

func (x *StatisticsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsResp.ProtoReflect.Descriptor instead.
func (*StatisticsResp) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{15}
}

func (x *StatisticsResp) GetTotalTests() int64 {
	if x != nil {
		return x.TotalTests
	}
	return 0
}

func (x *StatisticsResp) GetGlandFaceCount() int64 {
	if x != nil {
		return x.GlandFaceCount
	}
	return 0
}

func (x *StatisticsResp) GetNonGlandFaceCount() int64 {
	if x != nil {
		return x.NonGlandFaceCount
	}
	return 0
}

func (x *StatisticsResp) GetTrendData() string {
	if x != nil {
		return x.TrendData
	}
	return ""
}

func (x *StatisticsResp) GetLevelData() string {
	if x != nil {
		return x.LevelData
	}
	return ""
}

type ExportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	IsGlandFace   bool                   `protobuf:"varint,4,opt,name=is_gland_face,json=isGlandFace,proto3" json:"is_gland_face,omitempty"`
	HasFilter     bool                   `protobuf:"varint,5,opt,name=has_filter,json=hasFilter,proto3" json:"has_filter,omitempty"`
	Level         string                 `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportReq) Reset() {
	*x = ExportReq{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReq) ProtoMessage() {}

func (x *ExportReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReq.ProtoReflect.Descriptor instead.
func (*ExportReq) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{16}
}

func (x *ExportReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ExportReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ExportReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ExportReq) GetIsGlandFace() bool {
	if x != nil {
		return x.IsGlandFace
	}
	return false
}

func (x *ExportReq) GetHasFilter() bool {
	if x != nil {
		return x.HasFilter
	}
	return false
}

func (x *ExportReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type ExportResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	FileData      []byte                 `protobuf:"bytes,3,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResp) Reset() {
	*x = ExportResp{}
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResp) ProtoMessage() {}

func (x *ExportResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_diagnosis_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResp.ProtoReflect.Descriptor instead.
func (*ExportResp) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_diagnosis_proto_rawDescGZIP(), []int{17}
}

func (x *ExportResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ExportResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ExportResp) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *ExportResp) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_proto_diagnosis_diagnosis_proto protoreflect.FileDescriptor

const file_proto_diagnosis_diagnosis_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/diagnosis/diagnosis.proto\x12\tdiagnosis\"\x93\x01\n" +
	"\x12SubmitDiagnosisReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"image_path\x18\x02 \x01(\tR\timagePath\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\"m\n" +
	"\x13SubmitDiagnosisResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x03R\x06taskId\x12\x17\n" +
	"\atask_no\x18\x04 \x01(\tR\x06taskNo\"D\n" +
	"\fGetResultReq\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\x03R\bresultId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xf7\x02\n" +
	"\x13DiagnosisResultResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"image_path\x18\x04 \x01(\tR\timagePath\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\"\n" +
	"\ris_gland_face\x18\x06 \x01(\bR\visGlandFace\x12\x14\n" +
	"\x05level\x18\a \x01(\tR\x05level\x12;\n" +
	"\x19visualization_description\x18\t \x01(\tR\x18visualizationDescription\x12'\n" +
	"\x0freference_cases\x18\n" +
	" \x01(\tR\x0ereferenceCases\x12\x1b\n" +
	"\ttest_time\x18\v \x01(\tR\btestTime\x12%\n" +
	"\x0eskipped_images\x18\f \x01(\tR\rskippedImages\"+\n" +
	"\x10GetTaskStatusReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"\xa3\x01\n" +
	"\x11GetTaskStatusResp\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x17\n" +
	"\atask_no\x18\x02 \x01(\tR\x06taskNo\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1f\n" +
	"\vretry_count\x18\x04 \x01(\x05R\n" +
	"retryCount\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xed\x01\n" +
	"\x0eListResultsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\"\n" +
	"\ris_gland_face\x18\x06 \x01(\bR\visGlandFace\x12\x1d\n" +
	"\n" +
	"has_filter\x18\a \x01(\bR\thasFilter\x12\x14\n" +
	"\x05level\x18\b \x01(\tR\x05level\"a\n" +
	"\x0fListResultsResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x128\n" +
	"\arecords\x18\x02 \x03(\v2\x1e.diagnosis.DiagnosisResultRespR\arecords\"G\n" +
	"\x0fDeleteResultReq\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\x03R\bresultId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"8\n" +
	"\x10DeleteResultResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\";\n" +
	"\x0eBatchDeleteReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\\\n" +
	"\x0fBatchDeleteResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12#\n" +
	"\rdeleted_count\x18\x03 \x01(\x05R\fdeletedCount\"\x9a\x01\n" +
	"\x0fUpdateResultReq\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\x03R\bresultId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12;\n" +
	"\x19visualization_description\x18\x04 \x01(\tR\x18visualizationDescription\"8\n" +
	"\x10UpdateResultResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"b\n" +
	"\rStatisticsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\xca\x01\n" +
	"\x0eStatisticsResp\x12\x1f\n" +
	"\vtotal_tests\x18\x01 \x01(\x03R\n" +
	"totalTests\x12(\n" +
	"\x10gland_face_count\x18\x02 \x01(\x03R\x0eglandFaceCount\x12/\n" +
	"\x14non_gland_face_count\x18\x03 \x01(\x03R\x11nonGlandFaceCount\x12\x1d\n" +
	"\n" +
	"trend_data\x18\x05 \x01(\tR\ttrendData\x12\x1d\n" +
	"\n" +
	"level_data\x18\x06 \x01(\tR\tlevelData\"\xb7\x01\n" +
	"\tExportReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12\"\n" +
	"\ris_gland_face\x18\x04 \x01(\bR\visGlandFace\x12\x1d\n" +
	"\n" +
	"has_filter\x18\x05 \x01(\bR\thasFilter\x12\x14\n" +
	"\x05level\x18\x06 \x01(\tR\x05level\"k\n" +
	"\n" +
	"ExportResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1b\n" +
	"\tfile_data\x18\x03 \x01(\fR\bfileData\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename2\xf4\x05\n" +
	"\tDiagnosis\x12P\n" +
	"\x0fSubmitDiagnosis\x12\x1d.diagnosis.SubmitDiagnosisReq\x1a\x1e.diagnosis.SubmitDiagnosisResp\x12M\n" +
	"\x12GetDiagnosisResult\x12\x17.diagnosis.GetResultReq\x1a\x1e.diagnosis.DiagnosisResultResp\x12J\n" +
	"\rGetTaskStatus\x12\x1b.diagnosis.GetTaskStatusReq\x1a\x1c.diagnosis.GetTaskStatusResp\x12M\n" +
	"\x14ListDiagnosisResults\x12\x19.diagnosis.ListResultsReq\x1a\x1a.diagnosis.ListResultsResp\x12P\n" +
	"\x15DeleteDiagnosisResult\x12\x1a.diagnosis.DeleteResultReq\x1a\x1b.diagnosis.DeleteResultResp\x12K\n" +
	"\x12BatchDeleteResults\x12\x19.diagnosis.BatchDeleteReq\x1a\x1a.diagnosis.BatchDeleteResp\x12P\n" +
	"\x15UpdateDiagnosisResult\x12\x1a.diagnosis.UpdateResultReq\x1a\x1b.diagnosis.UpdateResultResp\x12D\n" +
	"\rGetStatistics\x12\x18.diagnosis.StatisticsReq\x1a\x19.diagnosis.StatisticsResp\x12:\n" +
	"\vExportExcel\x12\x14.diagnosis.ExportReq\x1a\x15.diagnosis.ExportResp\x128\n" +
	"\tExportPDF\x12\x14.diagnosis.ExportReq\x1a\x15.diagnosis.ExportRespB\"Z faceTest/backend/proto/diagnosisb\x06proto3"

var (
	file_proto_diagnosis_diagnosis_proto_rawDescOnce sync.Once
	file_proto_diagnosis_diagnosis_proto_rawDescData []byte
)

func file_proto_diagnosis_diagnosis_proto_rawDescGZIP() []byte {
	file_proto_diagnosis_diagnosis_proto_rawDescOnce.Do(func() {
		file_proto_diagnosis_diagnosis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_diagnosis_diagnosis_proto_rawDesc), len(file_proto_diagnosis_diagnosis_proto_rawDesc)))
	})
	return file_proto_diagnosis_diagnosis_proto_rawDescData
}

var file_proto_diagnosis_diagnosis_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_diagnosis_diagnosis_proto_goTypes = []any{
	(*SubmitDiagnosisReq)(nil),  // 0: diagnosis.SubmitDiagnosisReq
	(*SubmitDiagnosisResp)(nil), // 1: diagnosis.SubmitDiagnosisResp
	(*GetResultReq)(nil),        // 2: diagnosis.GetResultReq
	(*DiagnosisResultResp)(nil), // 3: diagnosis.DiagnosisResultResp
	(*GetTaskStatusReq)(nil),    // 4: diagnosis.GetTaskStatusReq
	(*GetTaskStatusResp)(nil),   // 5: diagnosis.GetTaskStatusResp
	(*ListResultsReq)(nil),      // 6: diagnosis.ListResultsReq
	(*ListResultsResp)(nil),     // 7: diagnosis.ListResultsResp
	(*DeleteResultReq)(nil),     // 8: diagnosis.DeleteResultReq
	(*DeleteResultResp)(nil),    // 9: diagnosis.DeleteResultResp
	(*BatchDeleteReq)(nil),      // 10: diagnosis.BatchDeleteReq
	(*BatchDeleteResp)(nil),     // 11: diagnosis.BatchDeleteResp
	(*UpdateResultReq)(nil),     // 12: diagnosis.UpdateResultReq
	(*UpdateResultResp)(nil),    // 13: diagnosis.UpdateResultResp
	(*StatisticsReq)(nil),       // 14: diagnosis.StatisticsReq
	(*StatisticsResp)(nil),      // 15: diagnosis.StatisticsResp
	(*ExportReq)(nil),           // 16: diagnosis.ExportReq
	(*ExportResp)(nil),          // 17: diagnosis.ExportResp
}
var file_proto_diagnosis_diagnosis_proto_depIdxs = []int32{
	3,  // 0: diagnosis.ListResultsResp.records:type_name -> diagnosis.DiagnosisResultResp
	0,  // 1: diagnosis.Diagnosis.SubmitDiagnosis:input_type -> diagnosis.SubmitDiagnosisReq
	2,  // 2: diagnosis.Diagnosis.GetDiagnosisResult:input_type -> diagnosis.GetResultReq
	4,  // 3: diagnosis.Diagnosis.GetTaskStatus:input_type -> diagnosis.GetTaskStatusReq
	6,  // 4: diagnosis.Diagnosis.ListDiagnosisResults:input_type -> diagnosis.ListResultsReq
	8,  // 5: diagnosis.Diagnosis.DeleteDiagnosisResult:input_type -> diagnosis.DeleteResultReq
	10, // 6: diagnosis.Diagnosis.BatchDeleteResults:input_type -> diagnosis.BatchDeleteReq
	12, // 7: diagnosis.Diagnosis.UpdateDiagnosisResult:input_type -> diagnosis.UpdateResultReq
	14, // 8: diagnosis.Diagnosis.GetStatistics:input_type -> diagnosis.StatisticsReq
	16, // 9: diagnosis.Diagnosis.ExportExcel:input_type -> diagnosis.ExportReq
	16, // 10: diagnosis.Diagnosis.ExportPDF:input_type -> diagnosis.ExportReq
	1,  // 11: diagnosis.Diagnosis.SubmitDiagnosis:output_type -> diagnosis.SubmitDiagnosisResp
	3,  // 12: diagnosis.Diagnosis.GetDiagnosisResult:output_type -> diagnosis.DiagnosisResultResp
	5,  // 13: diagnosis.Diagnosis.GetTaskStatus:output_type -> diagnosis.GetTaskStatusResp
	7,  // 14: diagnosis.Diagnosis.ListDiagnosisResults:output_type -> diagnosis.ListResultsResp
	9,  // 15: diagnosis.Diagnosis.DeleteDiagnosisResult:output_type -> diagnosis.DeleteResultResp
	11, // 16: diagnosis.Diagnosis.BatchDeleteResults:output_type -> diagnosis.BatchDeleteResp
	13, // 17: diagnosis.Diagnosis.UpdateDiagnosisResult:output_type -> diagnosis.UpdateResultResp
	15, // 18: diagnosis.Diagnosis.GetStatistics:output_type -> diagnosis.StatisticsResp
	17, // 19: diagnosis.Diagnosis.ExportExcel:output_type -> diagnosis.ExportResp
	17, // 20: diagnosis.Diagnosis.ExportPDF:output_type -> diagnosis.ExportResp
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_diagnosis_diagnosis_proto_init() }
func file_proto_diagnosis_diagnosis_proto_init() {
	if File_proto_diagnosis_diagnosis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_diagnosis_diagnosis_proto_rawDesc), len(file_proto_diagnosis_diagnosis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_diagnosis_diagnosis_proto_goTypes,
		DependencyIndexes: file_proto_diagnosis_diagnosis_proto_depIdxs,
		MessageInfos:      file_proto_diagnosis_diagnosis_proto_msgTypes,
	}.Build()
	File_proto_diagnosis_diagnosis_proto = out.File
	file_proto_diagnosis_diagnosis_proto_goTypes = nil
	file_proto_diagnosis_diagnosis_proto_depIdxs = nil
}
