// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/diagnosis/diagnosis.proto

package diagnosis

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Diagnosis_SubmitDiagnosis_FullMethodName       = "/diagnosis.Diagnosis/SubmitDiagnosis"
	Diagnosis_GetDiagnosisResult_FullMethodName    = "/diagnosis.Diagnosis/GetDiagnosisResult"
	Diagnosis_GetTaskStatus_FullMethodName         = "/diagnosis.Diagnosis/GetTaskStatus"
	Diagnosis_ListDiagnosisResults_FullMethodName  = "/diagnosis.Diagnosis/ListDiagnosisResults"
	Diagnosis_DeleteDiagnosisResult_FullMethodName = "/diagnosis.Diagnosis/DeleteDiagnosisResult"
	Diagnosis_BatchDeleteResults_FullMethodName    = "/diagnosis.Diagnosis/BatchDeleteResults"
	Diagnosis_UpdateDiagnosisResult_FullMethodName = "/diagnosis.Diagnosis/UpdateDiagnosisResult"
	Diagnosis_GetStatistics_FullMethodName         = "/diagnosis.Diagnosis/GetStatistics"
	Diagnosis_ExportExcel_FullMethodName           = "/diagnosis.Diagnosis/ExportExcel"
	Diagnosis_ExportPDF_FullMethodName             = "/diagnosis.Diagnosis/ExportPDF"
)

// DiagnosisClient is the client API for Diagnosis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 诊断服务
type DiagnosisClient interface {
	// 提交诊断任务（异步）
	SubmitDiagnosis(ctx context.Context, in *SubmitDiagnosisReq, opts ...grpc.CallOption) (*SubmitDiagnosisResp, error)
	// 获取诊断结果
	GetDiagnosisResult(ctx context.Context, in *GetResultReq, opts ...grpc.CallOption) (*DiagnosisResultResp, error)
	// 根据任务ID获取诊断状态
	GetTaskStatus(ctx context.Context, in *GetTaskStatusReq, opts ...grpc.CallOption) (*GetTaskStatusResp, error)
	// 获取诊断历史列表
	ListDiagnosisResults(ctx context.Context, in *ListResultsReq, opts ...grpc.CallOption) (*ListResultsResp, error)
	// 删除诊断结果
	DeleteDiagnosisResult(ctx context.Context, in *DeleteResultReq, opts ...grpc.CallOption) (*DeleteResultResp, error)
	// 批量删除诊断结果
	BatchDeleteResults(ctx context.Context, in *BatchDeleteReq, opts ...grpc.CallOption) (*BatchDeleteResp, error)
	// 更新诊断结果
	UpdateDiagnosisResult(ctx context.Context, in *UpdateResultReq, opts ...grpc.CallOption) (*UpdateResultResp, error)
	// 获取统计数据
	GetStatistics(ctx context.Context, in *StatisticsReq, opts ...grpc.CallOption) (*StatisticsResp, error)
	// 导出Excel
	ExportExcel(ctx context.Context, in *ExportReq, opts ...grpc.CallOption) (*ExportResp, error)
	// 导出PDF
	ExportPDF(ctx context.Context, in *ExportReq, opts ...grpc.CallOption) (*ExportResp, error)
}

type diagnosisClient struct {
	cc grpc.ClientConnInterface
}

func NewDiagnosisClient(cc grpc.ClientConnInterface) DiagnosisClient {
	return &diagnosisClient{cc}
}

func (c *diagnosisClient) SubmitDiagnosis(ctx context.Context, in *SubmitDiagnosisReq, opts ...grpc.CallOption) (*SubmitDiagnosisResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitDiagnosisResp)
	err := c.cc.Invoke(ctx, Diagnosis_SubmitDiagnosis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisClient) GetDiagnosisResult(ctx context.Context, in *GetResultReq, opts ...grpc.CallOption) (*DiagnosisResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnosisResultResp)
	err := c.cc.Invoke(ctx, Diagnosis_GetDiagnosisResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisClient) GetTaskStatus(ctx context.Context, in *GetTaskStatusReq, opts ...grpc.CallOption) (*GetTaskStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskStatusResp)
	err := c.cc.Invoke(ctx, Diagnosis_GetTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisClient) ListDiagnosisResults(ctx context.Context, in *ListResultsReq, opts ...grpc.CallOption) (*ListResultsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResultsResp)
	err := c.cc.Invoke(ctx, Diagnosis_ListDiagnosisResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisClient) DeleteDiagnosisResult(ctx context.Context, in *DeleteResultReq, opts ...grpc.CallOption) (*DeleteResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResultResp)
	err := c.cc.Invoke(ctx, Diagnosis_DeleteDiagnosisResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisClient) BatchDeleteResults(ctx context.Context, in *BatchDeleteReq, opts ...grpc.CallOption) (*BatchDeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchDeleteResp)
	err := c.cc.Invoke(ctx, Diagnosis_BatchDeleteResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisClient) UpdateDiagnosisResult(ctx context.Context, in *UpdateResultReq, opts ...grpc.CallOption) (*UpdateResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResultResp)
	err := c.cc.Invoke(ctx, Diagnosis_UpdateDiagnosisResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisClient) GetStatistics(ctx context.Context, in *StatisticsReq, opts ...grpc.CallOption) (*StatisticsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatisticsResp)
	err := c.cc.Invoke(ctx, Diagnosis_GetStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisClient) ExportExcel(ctx context.Context, in *ExportReq, opts ...grpc.CallOption) (*ExportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResp)
	err := c.cc.Invoke(ctx, Diagnosis_ExportExcel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisClient) ExportPDF(ctx context.Context, in *ExportReq, opts ...grpc.CallOption) (*ExportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResp)
	err := c.cc.Invoke(ctx, Diagnosis_ExportPDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagnosisServer is the server API for Diagnosis service.
// All implementations must embed UnimplementedDiagnosisServer
// for forward compatibility.
//
// 诊断服务
type DiagnosisServer interface {
	// 提交诊断任务（异步）
	SubmitDiagnosis(context.Context, *SubmitDiagnosisReq) (*SubmitDiagnosisResp, error)
	// 获取诊断结果
	GetDiagnosisResult(context.Context, *GetResultReq) (*DiagnosisResultResp, error)
	// 根据任务ID获取诊断状态
	GetTaskStatus(context.Context, *GetTaskStatusReq) (*GetTaskStatusResp, error)
	// 获取诊断历史列表
	ListDiagnosisResults(context.Context, *ListResultsReq) (*ListResultsResp, error)
	// 删除诊断结果
	DeleteDiagnosisResult(context.Context, *DeleteResultReq) (*DeleteResultResp, error)
	// 批量删除诊断结果
	BatchDeleteResults(context.Context, *BatchDeleteReq) (*BatchDeleteResp, error)
	// 更新诊断结果
	UpdateDiagnosisResult(context.Context, *UpdateResultReq) (*UpdateResultResp, error)
	// 获取统计数据
	GetStatistics(context.Context, *StatisticsReq) (*StatisticsResp, error)
	// 导出Excel
	ExportExcel(context.Context, *ExportReq) (*ExportResp, error)
	// 导出PDF
	ExportPDF(context.Context, *ExportReq) (*ExportResp, error)
	mustEmbedUnimplementedDiagnosisServer()
}

// UnimplementedDiagnosisServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiagnosisServer struct{}

func (UnimplementedDiagnosisServer) SubmitDiagnosis(context.Context, *SubmitDiagnosisReq) (*SubmitDiagnosisResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitDiagnosis not implemented")
}
func (UnimplementedDiagnosisServer) GetDiagnosisResult(context.Context, *GetResultReq) (*DiagnosisResultResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiagnosisResult not implemented")
}
func (UnimplementedDiagnosisServer) GetTaskStatus(context.Context, *GetTaskStatusReq) (*GetTaskStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedDiagnosisServer) ListDiagnosisResults(context.Context, *ListResultsReq) (*ListResultsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDiagnosisResults not implemented")
}
func (UnimplementedDiagnosisServer) DeleteDiagnosisResult(context.Context, *DeleteResultReq) (*DeleteResultResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDiagnosisResult not implemented")
}
func (UnimplementedDiagnosisServer) BatchDeleteResults(context.Context, *BatchDeleteReq) (*BatchDeleteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchDeleteResults not implemented")
}
func (UnimplementedDiagnosisServer) UpdateDiagnosisResult(context.Context, *UpdateResultReq) (*UpdateResultResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDiagnosisResult not implemented")
}
func (UnimplementedDiagnosisServer) GetStatistics(context.Context, *StatisticsReq) (*StatisticsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatistics not implemented")
}
func (UnimplementedDiagnosisServer) ExportExcel(context.Context, *ExportReq) (*ExportResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportExcel not implemented")
}
func (UnimplementedDiagnosisServer) ExportPDF(context.Context, *ExportReq) (*ExportResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportPDF not implemented")
}
func (UnimplementedDiagnosisServer) mustEmbedUnimplementedDiagnosisServer() {}
func (UnimplementedDiagnosisServer) testEmbeddedByValue()                   {}

// UnsafeDiagnosisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiagnosisServer will
// result in compilation errors.
type UnsafeDiagnosisServer interface {
	mustEmbedUnimplementedDiagnosisServer()
}

func RegisterDiagnosisServer(s grpc.ServiceRegistrar, srv DiagnosisServer) {
	// If the following call panics, it indicates UnimplementedDiagnosisServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Diagnosis_ServiceDesc, srv)
}

func _Diagnosis_SubmitDiagnosis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDiagnosisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServer).SubmitDiagnosis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diagnosis_SubmitDiagnosis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServer).SubmitDiagnosis(ctx, req.(*SubmitDiagnosisReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diagnosis_GetDiagnosisResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServer).GetDiagnosisResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diagnosis_GetDiagnosisResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServer).GetDiagnosisResult(ctx, req.(*GetResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diagnosis_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diagnosis_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServer).GetTaskStatus(ctx, req.(*GetTaskStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diagnosis_ListDiagnosisResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResultsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServer).ListDiagnosisResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diagnosis_ListDiagnosisResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServer).ListDiagnosisResults(ctx, req.(*ListResultsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diagnosis_DeleteDiagnosisResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServer).DeleteDiagnosisResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diagnosis_DeleteDiagnosisResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServer).DeleteDiagnosisResult(ctx, req.(*DeleteResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diagnosis_BatchDeleteResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServer).BatchDeleteResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diagnosis_BatchDeleteResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServer).BatchDeleteResults(ctx, req.(*BatchDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diagnosis_UpdateDiagnosisResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServer).UpdateDiagnosisResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diagnosis_UpdateDiagnosisResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServer).UpdateDiagnosisResult(ctx, req.(*UpdateResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diagnosis_GetStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServer).GetStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diagnosis_GetStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServer).GetStatistics(ctx, req.(*StatisticsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diagnosis_ExportExcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServer).ExportExcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diagnosis_ExportExcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServer).ExportExcel(ctx, req.(*ExportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diagnosis_ExportPDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServer).ExportPDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diagnosis_ExportPDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServer).ExportPDF(ctx, req.(*ExportReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Diagnosis_ServiceDesc is the grpc.ServiceDesc for Diagnosis service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Diagnosis_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "diagnosis.Diagnosis",
	HandlerType: (*DiagnosisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitDiagnosis",
			Handler:    _Diagnosis_SubmitDiagnosis_Handler,
		},
		{
			MethodName: "GetDiagnosisResult",
			Handler:    _Diagnosis_GetDiagnosisResult_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _Diagnosis_GetTaskStatus_Handler,
		},
		{
			MethodName: "ListDiagnosisResults",
			Handler:    _Diagnosis_ListDiagnosisResults_Handler,
		},
		{
			MethodName: "DeleteDiagnosisResult",
			Handler:    _Diagnosis_DeleteDiagnosisResult_Handler,
		},
		{
			MethodName: "BatchDeleteResults",
			Handler:    _Diagnosis_BatchDeleteResults_Handler,
		},
		{
			MethodName: "UpdateDiagnosisResult",
			Handler:    _Diagnosis_UpdateDiagnosisResult_Handler,
		},
		{
			MethodName: "GetStatistics",
			Handler:    _Diagnosis_GetStatistics_Handler,
		},
		{
			MethodName: "ExportExcel",
			Handler:    _Diagnosis_ExportExcel_Handler,
		},
		{
			MethodName: "ExportPDF",
			Handler:    _Diagnosis_ExportPDF_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/diagnosis/diagnosis.proto",
}
