// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/upload.proto

package upload

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadImageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageReq) Reset() {
	*x = UploadImageReq{}
	mi := &file_proto_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageReq) ProtoMessage() {}

func (x *UploadImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageReq.ProtoReflect.Descriptor instead.
func (*UploadImageReq) Descriptor() ([]byte, []int) {
	return file_proto_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadImageReq) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadImageReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadImageReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadImageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ImagePath     string                 `protobuf:"bytes,3,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	FileSize      int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResp) Reset() {
	*x = UploadImageResp{}
	mi := &file_proto_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResp) ProtoMessage() {}

func (x *UploadImageResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResp.ProtoReflect.Descriptor instead.
func (*UploadImageResp) Descriptor() ([]byte, []int) {
	return file_proto_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadImageResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UploadImageResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UploadImageResp) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *UploadImageResp) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UploadImageResp) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type BatchUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*UploadImageReq      `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUploadReq) Reset() {
	*x = BatchUploadReq{}
	mi := &file_proto_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUploadReq) ProtoMessage() {}

func (x *BatchUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUploadReq.ProtoReflect.Descriptor instead.
func (*BatchUploadReq) Descriptor() ([]byte, []int) {
	return file_proto_upload_proto_rawDescGZIP(), []int{2}
}

func (x *BatchUploadReq) GetFiles() []*UploadImageReq {
	if x != nil {
		return x.Files
	}
	return nil
}

type BatchUploadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Results       []*UploadImageResp     `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUploadResp) Reset() {
	*x = BatchUploadResp{}
	mi := &file_proto_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUploadResp) ProtoMessage() {}

func (x *BatchUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUploadResp.ProtoReflect.Descriptor instead.
func (*BatchUploadResp) Descriptor() ([]byte, []int) {
	return file_proto_upload_proto_rawDescGZIP(), []int{3}
}

func (x *BatchUploadResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BatchUploadResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BatchUploadResp) GetResults() []*UploadImageResp {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_proto_upload_proto protoreflect.FileDescriptor

const file_proto_upload_proto_rawDesc = "" +
	"\n" +
	"\x12proto/upload.proto\x12\x06upload\"l\n" +
	"\x0eUploadImageReq\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"\x90\x01\n" +
	"\x0fUploadImageResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1d\n" +
	"\n" +
	"image_path\x18\x03 \x01(\tR\timagePath\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\">\n" +
	"\x0eBatchUploadReq\x12,\n" +
	"\x05files\x18\x01 \x03(\v2\x16.upload.UploadImageReqR\x05files\"j\n" +
	"\x0fBatchUploadResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x121\n" +
	"\aresults\x18\x03 \x03(\v2\x17.upload.UploadImageRespR\aresults2\x8e\x01\n" +
	"\x06Upload\x12>\n" +
	"\vUploadImage\x12\x16.upload.UploadImageReq\x1a\x17.upload.UploadImageResp\x12D\n" +
	"\x11BatchUploadImages\x12\x16.upload.BatchUploadReq\x1a\x17.upload.BatchUploadRespB\x1fZ\x1dfaceTest/backend/proto/uploadb\x06proto3"

var (
	file_proto_upload_proto_rawDescOnce sync.Once
	file_proto_upload_proto_rawDescData []byte
)

func file_proto_upload_proto_rawDescGZIP() []byte {
	file_proto_upload_proto_rawDescOnce.Do(func() {
		file_proto_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_upload_proto_rawDesc), len(file_proto_upload_proto_rawDesc)))
	})
	return file_proto_upload_proto_rawDescData
}

var file_proto_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_upload_proto_goTypes = []any{
	(*UploadImageReq)(nil),  // 0: upload.UploadImageReq
	(*UploadImageResp)(nil), // 1: upload.UploadImageResp
	(*BatchUploadReq)(nil),  // 2: upload.BatchUploadReq
	(*BatchUploadResp)(nil), // 3: upload.BatchUploadResp
}
var file_proto_upload_proto_depIdxs = []int32{
	0, // 0: upload.BatchUploadReq.files:type_name -> upload.UploadImageReq
	1, // 1: upload.BatchUploadResp.results:type_name -> upload.UploadImageResp
	0, // 2: upload.Upload.UploadImage:input_type -> upload.UploadImageReq
	2, // 3: upload.Upload.BatchUploadImages:input_type -> upload.BatchUploadReq
	1, // 4: upload.Upload.UploadImage:output_type -> upload.UploadImageResp
	3, // 5: upload.Upload.BatchUploadImages:output_type -> upload.BatchUploadResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_upload_proto_init() }
func file_proto_upload_proto_init() {
	if File_proto_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_upload_proto_rawDesc), len(file_proto_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_upload_proto_goTypes,
		DependencyIndexes: file_proto_upload_proto_depIdxs,
		MessageInfos:      file_proto_upload_proto_msgTypes,
	}.Build()
	File_proto_upload_proto = out.File
	file_proto_upload_proto_goTypes = nil
	file_proto_upload_proto_depIdxs = nil
}
